config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  resources :products, :categories do
    resources :comments, :categories
  end

  resources :products, only: [:index] do
  end

  namespace :api do
    get 'users/email_exists', to: 'users#email_exists'

    resources :products, only: [:index]
  end

  resources :concrete_products, only: [] do
    collection do
      post :add_to_cart
    end
  end
  resources :carts, only: [:index] do
    collection do
      post :confirm
    end
  end

  namespace :user_panel, path: 'user' do
    root to: 'profile#index'

    resources :order_history, only: %i[index show]
    resources :account_management, only: %i[index show update]
    resources :orders, only: %i[show index] do
      member do
        patch :confirm
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :owner, polymorphic: true
  has_many :order_items

  scope :pending, -> { where(status: PENDING_ORDER_STATUS) }

  CART_STATUS = 'cart'.freeze
  PENDING_ORDER_STATUS = 'pending_order'.freeze
  CONFIRMED_ORDER_STATUS = 'confirmed_order'.freeze
end

app/controllers/user_panel/account_management_controller.rb
module UserPanel
  class AccountManagementController < ApplicationController
    def show
      @user = current_user
    end

    def update
      @user = current_user
      flash[:notice] = if @user.update_attributes(post_params)
                         'Your account informations was changed successfully'
                       else
                         'Error'
                       end
      redirect_to user_panel_account_management_path
    end

    private

    def post_params
      params.require(:user).permit(:name, :surname, :email, :address, :city, :zip_code, :phone, :country)
    end
  end
end

app/controllers/user_panel/order_history_controller.rb
module UserPanel
  class OrderHistoryController < ApplicationController
    def index
      @history_orders = current_user.orders
    end

    def show
      @history_order = current_user.orders.find(params[:id])
    end
  end
end

app/controllers/user_panel/orders_controller.rb
module UserPanel
  class OrdersController < ApplicationController
    before_action :authenticate_user!

    def index
      @orders = current_user.orders
    end

    def show
      @order = attach_order
    end

    def confirm
      order = current_user.orders.pending.find(params[:id])
      order.update(
        comment: params[:order][:comment],
        status: Order::CONFIRMED_ORDER_STATUS
      )

      redirect_to user_panel_order_path(order)
    end

    private

    def attach_order
      order = current_user.orders.find_by(id: params[:id])
      return order if order

      order = current_guest.orders.find_by(id: params[:id])
      raise ActiveRecord::RecordNotFound unless order

      order.update owner: current_user

      order
    end
  end
end

app/controllers/user_panel/profile_controller.rb
module UserPanel
  class ProfileController < ApplicationController
    before_action :authenticate_user!

    def index; end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/user_panel/orders/index.html.slim
table.table
  thead
    tr
      th Numer zamówienia
      th Ilość produktów
      th 
  tbody    
    - @orders.each do |order|
      tr
        td= link_to "Zamówienie numer ##{order.id}", user_panel_order_path(order)
        td= order.order_items.size
          

app/views/user_panel/orders/show.html.slim
h1= "Status zamówienia #{@order.status}"

table.table
  - @order.order_items.each do |item|
    tr
      td= item.product.name

- if @order.status == Order::PENDING_ORDER_STATUS

  = form_for @order, url: confirm_user_panel_order_path(@order) do |f|

    .form_group
      = f.text_area :comment, class: 'form-control', placeholder: 'Uwagi do zamówienia'
    .form_group  
    = f.submit 'Złóż zamówienie', class: 'btn btn-primary'
- else
  = button_to('Powrót do strony głównej', products_path, method: :get, class: "btn btn-primary")