config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  resources :products, :categories do
    resources :comments, :categories
  end

  resources :products, only: [:index] do
  end

  namespace :api do
    get 'users/email_exists', to: 'users#email_exists'

    resources :products, only: [:index]
  end

  resources :concrete_products, only: [] do
    collection do
      post :add_to_cart
    end
  end
  resources :carts, only: [:index] do
    collection do
      post :confirm
    end
  end

  namespace :user_panel, path: 'user' do
    root to: 'profile#index'

    resources :order_history, only: %i[index show]
    resources :account_management, only: %i[index show update]
    resources :orders, only: %i[show index] do
      member do
        patch :confirm
      end
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :productrates
  has_many :comments
  has_many :concrete_products
  belongs_to :category
  validates_presence_of :category
  validates_presence_of :name

  def all_concrete_products
    concrete_products.uniq(&:color)
  end

  def rate
    productrates.sum(:rate) / productrates.count
  rescue StandardError
    0
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = if params[:sort]
                  ProductProvider.new.sort(params[:sort])
                else
                  Product.all
                end
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.productrates.create(rate: params[:product][:rate])
      redirect_to(@product)
    else
      render 'index'
    end
  end

  def add_to_cart
    product = Product.find(params[:id])
    outcome = AddToCart.run(guest: current_guest, product: product)

    flash[:notice] = if outcome.valid?
                       'Dodano do koszyka'
                     else
                       outcome.errors.full_messages
                     end

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:rate)
  end
end

app/views/products/index.html.slim
.p-3
  h2 All products:
  a
  #order-by_asc
    form
      select name="sort" class="btn btn-outline-dark"
        option value="name asc"  Name
        option value="rate asc"  Rate
      input type="submit" class="btn btn-outline-dark" value="Sort Ascending"
  #order-by_desc
    form
      select name="sort" class="btn btn-outline-dark"
        option value="name desc"  Name
        option value="rate desc"  Rate
      input type="submit" class="btn btn-outline-dark" value="Sort Descending"


  - @products.each do |product|
      p
        a href=product_path(product)
          = product.name
= button_to('Koszyk zamówień', carts_path, method: :get, class: "btn btn-primary")

app/views/products/show.html.slim
= link_to products_path do
  strong back
.p-3
    ul.errors
        - flash.each do |key, value|
            li = "#{value}"
    div
        h1= @product.name
        div 
				/ price: #{@product.price}
        - if @product.promoted
                = "This product is promoted!"
                br
        - if @product.rate != 0
                = "Average rate of this product: #{@product.rate}"
        - else
                = "This product has no rates."
        ul
            - @product.comments.each do |comment|
                    li = "#{comment.content} (#{comment.created_at})" 
    - if @product.concrete_products.size > 0                
      = form_tag add_to_cart_concrete_products_path do |f|
        - @product.concrete_products.each do |concrete_product|
            .form-check
              = radio_button_tag :id, concrete_product.id
              = label_tag "Size: #{concrete_product.size}"
              = label_tag "Price: #{concrete_product.price}"
              = label_tag "Color: #{concrete_product.color}"
              = label_tag "On stock: #{concrete_product.amount}" 
        = submit_tag "Dodaj do koszyka"

    - if user_signed_in?
        = form_for(@product) do |f|
            = f.radio_button :rate, 1
            = f.label :rate, '1', :value => 1
            = f.radio_button :rate, 2
            = f.label :rate, '2', :value => 2
            = f.radio_button :rate, 3
            = f.label :rate, '3', :value => 3
            = f.radio_button :rate, 4
            = f.label :rate, '4', :value => 4
            = f.radio_button :rate, 5
            = f.label :rate, '5', :value => 5
            = f.submit "Rate product"
        = form_for([@product, @product.comments.build]) do |f|
            div.field
            = f.text_field :content
            div
            = f.submit "Add comment"